### PR TITLE
playlist following

### PR DESCRIPTION
**Pull request by ArdaKurucim**

### CODE REVIEW

**Comment by QNS1** [comment]
agreed

**Comment by useragents** [comment]
No option for profile followers + playlist followers. This request only has playlist following

**Comment by ArdaKurucim** [comment]
It definitely has options it just recognizes from link if its playlist or not

**Comment by ArdaKurucim** [comment]
> No option for profile followers + playlist followers. This request only has playlist following

please check it again

**Comment by ArdaKurucim** [comment]
if it finds /playlist/ in the link it just sends playlist liking but if not it just sends normal followers

**Pull request closed without merging**
